# Generated by Django 5.0.7 on 2024-08-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icecreame', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='Brand',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='Price',
        ),
        migrations.AddField(
            model_name='menu',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='menu',
            name='flavour',
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name='menu',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
